---
version: "3.7"

services:
  cognito-lambda-builder:
    image: ${NAME}:${TAG}
    build:
      context: .
    volumes:
      - ./src:/src
      - ./.build:/.build
      - ./.cache:/.cache
      - ./.package:/.package
      - ./.wheelhouse:/.wheelhouse
      - ./scripts/packager.sh:/scripts/packager.sh

