---
version: "3.7"

services:
  squid:
    image: sameersbn/squid:3.5.27-2
    ports:
      - "3128:3128"
    volumes:
      - squid_cache:/var/spool/squid
      - ./squid.conf:/etc/squid/squid.conf
    restart: always

volumes:
  squid_cache: