---
version: "3.7"

services:
  lambda:
    image: lambci/lambda:python3.7
    volumes:
      - ./.build:/var/task:ro,delegated
    command: lambda.lambdahandler
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: root
