---
version: "3.7"

services:
  cognito-lambda-builder:
    image: ${NAME}:${TAG}
    build:
      context: .
    volumes:
      - ./src:/src
      - ./.build:/.build
      - ./.package:/.package
      - ./scripts/custom_packager.sh:/scripts/packager.sh
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: root
    ports:
      - 3306:3306