---
version: "3.7"

services:
  cognito-lambda-builder:
    image: ${NAME}:${TAG}
    build:
      context: .
#      args:
#        ftp_proxy: "http://127.0.0.1:3128"
#        http_proxy: "http://127.0.0.1:3128"
#        https_proxy: "http://127.0.0.1:3128"
    volumes:
      - ./src:/src
      - ./.build:/.build
      - ./.cache:/.cache
      - ./.package:/.package
      - ./.wheelhouse:/.wheelhouse
      - ./scripts/packager.sh:/scripts/packager.sh

